### PR TITLE
Fix #35: Cart alert and expiry

### LINKED ISSUE #35: Cart expiry and alert
Display confirm box before 10 minutes of cart expiry
If clicked on

- OK: Extend the cart session for another 30 minutes
- Cancel: Expire the session after 10 minutes

Cart expiry should happen after 30 minutes by itself instead of an action trigger

### PR DESCRIPTION
**Pull request by priyakvs**
- After 25 minutes (now its 1 minute) of inactivity (no actions performed), custom bootstrap modal pops up with ok and cancel button.

- On click of OK, session gets extended to another 30 minutes(3 minutes now). On click of cancel, session expires in 30 minutes if no action is invoked in between. If no action is performed, session resets every 30 minutes.

- This is based on user session. So, have changed the messaged to 'Your session' instead of 'Your shopping cart'. Please see the image for the message.

image

- Admin's session stays for 8 hours with no interruption by this alert or session.

- If a book is added to cart and then the browser itself is closed, the book will not be available for other users unless this browser is opened again. Please let me know if that should be handled. I thought of options but couldn't find a solution. One way I thought would work is running a rake task everyday at midnight or after midnight (2 or 3 AM) when traffic would be low. The rake task will put all pending books with no author to available state.

- I have added bootstrap to the application because of which fonts have changed which I will take care in 'css and layouts' issue.

Please let me know if there are other things to consider.

### CODE REVIEW

**Comment by priyakvs** [comment]
I did commit --amend to change a structure but coveralls failed saying coverage decreased by 0.08. Is there a work around for this?

**Comment by hortongn** [comment]
> I did commit --amend to change a structure but coveralls failed saying coverage decreased by 0.08. Is there a work around for this?

@priyakvs I don't see any issue with the coverage.  I think coveralls is just confused. 😄

**Review by hortongn — CHANGES_REQUESTED** [review]
@priyakvs Everything looks good.  Please set the expiry times to the real values and push it up again.  Then I'll merge.

**Comment by priyakvs** [comment]
@hortongn Updated with real timings and pushed.

**Review by hortongn — APPROVED** [review]
@priyakvs Nice job!  merging

**Pull request merged**
