### PR TITLE
Dockerization changes for Adopt a Book

### PR DESCRIPTION
**Pull request by bhanutejags**
* Fixed mimemagic dependency issue by upgrading Rails, from 5.2.4 to 5.2.6.
  * https://github.com/rails/rails/issues/41750
  * https://github.com/mimemagicrb/mimemagic/issues/139 
* Dockerization changes

### CODE REVIEW

**Review by hortongn — CHANGES_REQUESTED** [review]
@bhanutejags Can we add some instructions to the README that explain how to start the application via Docker?

**Review by hortongn — CHANGES_REQUESTED** [review]
@bhanutejags Looks good.  Please squash the commits and rebase and I'll then merge.

**Comment by bhanutejags** [comment]
> @bhanutejags Can we add some instructions to the README that explain how to start the application via Docker?

Done.

**Comment by bhanutejags** [comment]
> @bhanutejags Looks good. Please squash the commits and rebase and I'll then merge.

Done.

**Review by hortongn — APPROVED** [review]

**Pull request merged**
